name: admin_panel
description: Admin apps to control Af-Fix Smartphone Repair

publish_to: 'none'

version: 2.0.3+10

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: any

  # UI/UX
  cupertino_icons: ^1.0.2
  sliding_sheet: ^0.5.2
  rounded_loading_button: ^2.0.9
  lottie:
  fl_chart: ^0.60.0
  flutter_advanced_avatar: ^1.0.0+1
  shimmer: ^2.0.0
  flutter_slidable: ^2.0.0
  badges: ^3.0.2
  percent_indicator: ^4.0.0
  another_xlider: ^1.1.0
  flutter_staggered_animations: ^1.0.0
  dynamic_color: ^1.3.0
  stacked_bar_chart: ^1.1.0+2
  masonry_grid: ^1.0.0
  chart_sparkline: ^1.0.12
  grouped_list: ^5.1.2
  quds_popup_menu: ^0.0.1+1

  # API Services
  firebase_core_platform_interface: ^4.5.2
  flutterfire_cli: ^0.2.7
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  firebase_database: ^10.0.9
  firebase_storage: ^11.0.10
  firebase_messaging: ^14.2.1
  restart_app: ^1.1.0
  gsheets: ^0.4.2
  flutter_mailer: ^2.0.2
  
  
  # State Management
  get: ^4.6.3

  # I/O
  get_storage: ^2.0.3
  sqflite: ^2.0.0+4
  url_launcher: ^6.1.2
  share_plus: ^5.0.0
  file_picker: ^5.0.1
  extended_image: ^6.0.1
  cross_file: ^0.3.3+2
  
  # Data Models
  intl: ^0.17.0
  flutter_native_contact_picker: ^0.0.3
  path_provider: ^2.0.9
  pdf:
  syncfusion_flutter_pdfviewer: ^20.1.55-beta
  flutter_app_badger: ^1.2.0
  device_info_plus: ^8.0.0
  image_picker: ^0.8.4+2
  image_cropper: ^3.0.1
  jiffy: ^5.0.0
  flutter_typeahead: ^4.0.0
  quick_actions: ^1.0.1
  connectivity_checker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons:
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "assets/images/icon_background.png"
  adaptive_icon_foreground: "assets/images/icon_foreground.png"


#   flutter_native_splash: 0.3.0

# flutter_native_splash:
#   color: "#ffffff"
#   image: "assets/images/splash_dark.png"
#   color_dark: "#1a1a1a"
#   image_dark: "assets/images/splash_light.png"
#   android: true
#   ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/lottie/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
