name: admin_panel
description: Admin apps to control Af-Fix Smartphone Repair

publish_to: 'none'

version: 2.0.2+5

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI/UX
  cupertino_icons: ^1.0.2
  sliding_sheet: ^0.5.0
  rounded_loading_button: ^1.0.18
  lottie:
  fl_chart: ^0.36.4
  liquid_pull_to_refresh: ^3.0.0
  flutter_advanced_avatar: ^1.0.0+1
  shimmer: ^2.0.0
  flutter_slidable: ^0.6.0
  badges: ^2.0.1
  percent_indicator: ^3.0.1
  another_xlider: ^1.0.0
  line_icons: ^2.0.1

  # API Services
  firebase_core: ^1.5.0
  cloud_firestore: ^2.5.0
  firebase_auth: ^3.0.2
  flutter_mailer: ^2.0.0
  firebase_database: ^8.0.0
  firebase_storage: ^10.0.3

  # Native Hardware
  esc_pos_bluetooth: ^0.2.8
  esc_pos_utils: ^0.3.6
  flutter_bluetooth_basic: ^0.1.5

  # State Management
  get: ^4.3.8

  # I/O
  get_storage: ^2.0.3
  sqflite: ^2.0.0+4
  url_launcher: ^6.0.9
  share_plus: ^2.1.4
  file_picker: ^4.2.0

  # Data Models
  intl: ^0.17.0
  flutter_native_contact_picker: ^0.0.3
  path_provider: ^2.0.2
  pdf:
  flutter_full_pdf_viewer: ^1.0.6
  flutter_app_badger: ^1.2.0
  device_info_plus: ^2.1.0
  image_picker: ^0.8.4+2
  image_cropper: ^1.4.1
  jiffy: ^4.1.0
  flutter_typeahead: ^3.2.1
  quick_actions: ^0.6.0+7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons:
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon_foreground.png"


#   flutter_native_splash: 0.3.0

# flutter_native_splash:
#   color: "#ffffff"
#   image: "assets/images/splash_dark.png"
#   color_dark: "#1a1a1a"
#   image_dark: "assets/images/splash_light.png"
#   android: true
#   ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/lottie/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
